"""Write dashboard/js/config.js from root .env values."""

from pathlib import Path
import os

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")

url = os.getenv("SUPABASE_URL", "https://vtlfbpxcequpfkivxzgf.supabase.co")
anon_key = (
    os.getenv("SUPABASE_PUBLISHABLE_KEY")
    or os.getenv("SUPABASE_ANON_KEY")
    or "YOUR_SUPABASE_ANON_KEY"
)

config_path = ROOT / "dashboard" / "js" / "config.js"
config_path.write_text(
    f"""// Generated by data/sync_dashboard_config.py
window.SUPABASE_CONFIG = {{
  url: '{url}',
  anonKey: '{anon_key}',
}};
""",
    encoding="utf-8",
)

print(f"Wrote {config_path}")
