const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
}

function readExistingConfig(configPath) {
  if (!fs.existsSync(configPath)) {
    return null;
  }
  const text = fs.readFileSync(configPath, 'utf8');
  const matchUrl = text.match(/url:\s*'([^']+)'/);
  const matchKey = text.match(/anonKey:\s*'([^']+)'/);
  return {
    url: matchUrl ? matchUrl[1] : null,
    anonKey: matchKey ? matchKey[1] : null,
  };
}

function quoteValue(value) {
  return String(value ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

const outputPath = path.join(rootDir, 'dashboard', 'js', 'config.js');
const existing = readExistingConfig(outputPath);
const url = process.env.SUPABASE_URL || existing?.url || 'https://vtlfbpxcequpfkivxzgf.supabase.co';
const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY || existing?.anonKey || 'YOUR_SUPABASE_ANON_KEY';

const content = `// Generated by scripts/sync_dashboard_config.cjs
window.SUPABASE_CONFIG = {
  url: '${quoteValue(url)}',
  anonKey: '${quoteValue(anonKey)}',
};
`;

fs.writeFileSync(outputPath, content, 'utf8');
console.log(`Wrote ${path.relative(rootDir, outputPath)}`);
